# Generated by Django 2.1.15 on 2021-07-03 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210702_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_creation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
