# Generated by Django 3.2.8 on 2021-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_edition', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=180)),
                ('model', models.CharField(max_length=180)),
                ('price', models.DecimalField(decimal_places=3, editable=False, max_digits=9)),
                ('quantity', models.IntegerField(editable=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=180, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_in_storage', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_edition', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_edition', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
