# Generated by Django 3.2.8 on 2021-11-02 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='fk_user_creation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fk_header_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='header',
            name='fk_user_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_header_user_edition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_accounting', to='equipo.accounting'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_header', to='equipo.header'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_last_assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_last_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_last_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_last_unidad', to='unidades.unidad'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_unidad', to='unidades.unidad'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_user_creation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_user_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_equipo_user_edition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounting',
            name='fk_user_creation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fk_accounting_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounting',
            name='fk_user_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_accouting_user_edition', to=settings.AUTH_USER_MODEL),
        ),
    ]
