# Generated by Django 3.2.8 on 2021-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_edition', models.DateTimeField(blank=True, default=None, null=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, null=True, to='auth.Group')),
            ],
        ),
    ]
