# Generated by Django 3.2.5 on 2021-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos_geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentogeo',
            old_name='departamento',
            new_name='name',
        ),
    ]
