# Generated by Django 3.2.8 on 2021-11-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas', '0001_initial'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='fk_oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas.oficina'),
        ),
    ]
